const SKILL_DESCRIPTIONS = {
  rune_q: "[Frost Shard] Базовое ледяное копье: летит по прямой, пробивает до 5 целей и исчезает после 5-го попадания или конца дальности.",
  rune_w: "[Chain Lightning] Базовая цепная молния: прыгает к ближайшей цели, до 7 отскоков, обрывается если в радиусе нет врагов.",
  rune_e: "[Meteor] Базовый метеор: наносит урон в малом радиусе при падении, затем ударная волна (50% урона, радиус x3).",
  duo_qq: "[Frost Spear] Усиленное копье: +25% размер снаряда, больше дальность и пробитие, +20% урон.",
  duo_qw: "[Thunderfrost Spear] Вылетает обычное ледяное копье; при первом попадании из цели стартует обычная цепная молния.",
  duo_qe: "[Cryo Meteor] Падает обычный метеор; после удара вместе с волной выпускает 5 обычных ледяных копий в стороны.",
  duo_ww: "[Chain Storm] Усиленная молния: +15% урон, 15 отскоков и дальность отскоков/начального луча x1.5.",
  duo_we: "[Ball Lightning] Шаровая молния: светящийся плазменный шар перескакивает с врага на врага; при каждом приземлении / у узла наносит AOE-урон по области вокруг точки. Не цепная молния по «проводке» между целями без объёма удара.",
  duo_ee: "[Great Meteor] Усиленный метеор: +50% урон и +100% к размеру; ударные волны также масштабируются от увеличенного размера.",
  combo_qqq: "[Cold Embrace] Ледяной панцирь: герой обездвижен и неуязвим, накапливает входящий урон, затем взрывается волной и отталкивает обычных врагов к краю волны.",
  combo_qqw: "[Frost Nova] Морозное кольцо: расходящаяся волна вокруг героя, урон и обездвиживание врагов.",
  combo_qqe:
    "[Enhance Armament! Release Recollection!] Волна холода 3 с (800); лозы; DoT −10/0.1 с. Розы заполняют диск зоны; после скилла остаются как ледяные розы‑мины (наступление героя/врага или взрыв через 10 с).",
  combo_qwq: "[Frost Ravage] Ледяные пики: 3 расходящиеся волны шипов из земли вокруг героя; внешние волны плотнее, каждая волна слегка отталкивает обычных врагов к следующей.",
  combo_qww: "[Fear Aura] Аура страха: вокруг героя расширяется круг, затем аура держится 3с; страх на врагах длится 5с.",
  combo_qwe: "[Teleport] Телепорт: мгновенный перенос к точке курсора в пределах дальности.",
  combo_qeq: "[Proximity Mine] Мина: ставится в точке каста, срабатывает при наступании врага, взрывается волной как у метеора; в одной точке можно ставить несколько мин.",
  combo_qew: "[Fire Ground] Огненная лужа: в точке каста появляется красная зона и наносит периодический урон врагам внутри.",
  combo_qee: "[Frost Resonator] Ледяной резонатор: кристалл у курсора (не дальше 700 от героя), 7 с, радиус 500. Любой урон по цели в зоне (включая по вам) триггерит срез 20% от величины урона по HP всех врагов в зоне (не считается уроном навыка, без рекурсии). Новый каст заменяет старый кристалл.",
  combo_wqq: "[Frost Rain] Ледяной дождь: круглая зона, в которую с неба падают малые льдинки; каждая наносит урон, эффект длится пока не упадут все льдинки.",
  combo_wqw: "[Solar Beam] Луч: каналящийся лазер на 5с, ширина как 2 персонажа, нельзя двигаться, поворот в 5 раз медленнее, урон 10 тиков/с.",
  combo_wqe: "[Lightning Dash] Молниеносный рывок: короткая молниеносная сфера, затем рывок к курсору со скоростью 300% и урон/стан всем целям на пути.",
  combo_wwq: "[Energy Shield] Щит поглощения: даёт броню в размере 50% от макс. HP; броня полностью гасит входящий урон, пока не закончится.",
  combo_www: "[Lightning Anchor] Якорь: в точку курсора (≤700 от героя), 7 с, без урона. В момент постановки цепляет только врагов в радиусе 600; вошедшие позже игнорируют якорь. Обычные: притяжение к кольцу 200, −50% скорости; босс/элита: цепь и замедление без притяжения, срыв при выходе за 600. Новый якорь отменяет предыдущий.",
  combo_wwe: "[Black Hole] Чёрная дыра: в радиусе стан и притяжение к центру со скоростью 25% от скорости врага; до 150% радиуса враги только притягиваются. В центральной области наносит урон раз в 1с.",
  combo_weq: "[Repulse] Ударная волна: только сильное отталкивание врагов на большую дистанцию, без урона.",
  combo_wew: "[Overcharge] Перегрузка (Overcharge): на 10с убирает КД у 2-рунных скиллов; текущий КД 2-рунных при активации сразу сбрасывается.",
  combo_wee: "[Mirror Clone] Зеркальный клон: неподвижная копия на 10 с (или до уничтожения), 50% от текущего HP. Повторяет касты с 40% силы с позиции клона к курсору; точечные навыки — в ту же точку или на край дальности от клона. Враги целят ближайшую цель (при ничьей — клон). Щит на клоне отдельно, макс. 1 активный на сущность.",
  combo_eqq: "[Ice Wall] Ледяная стена: снаряд летит по направлению каста; при попадании создает подковообразную ледяную стену на 10с (ножки по направлению полета), враги на стене сдвигаются внутрь, стена работает как препятствие.",
  combo_eqw: "[Fire Yo-Yo] Йо-йо: из героя вылетает большой круглый снаряд (примерно x3 от размера героя) на веревке; на максимальной дальности разворачивается и возвращается обратно, нанося урон и на вылете, и на возврате.",
  combo_eqe: "[Fire Step] Огненный форсаж: +50% к скорости передвижения на 5с; по траектории бега остается огненный след, наносящий периодический урон врагам.",
  combo_ewq: "[Gale Force] Порыв ветра: формирует прямоугольную область по направлению каста; внутри дует сильный ветер и сдувает врагов вперед.",
  combo_eww: "[Volcano Turret] Вулкан: в точке каста появляется треугольный вулкан-турель, дальность атаки 1000; стреляет по ближайшим врагам 2 раза в секунду, запас 20 снарядов. Снаряд поражает одну цель или исчезает при вылете дальше 1000 от вулкана.",
  combo_ewe: "[Elemental Fury] Элементальный вихрь (каналинг): 5с герой вращается (1 оборот/с), получает +20% скорости и не может кастовать другие скиллы; каждые 0.1с во все стороны вылетает случайный базовый снаряд (ледяной осколок Q / цепная молния W / метеор E).",
  combo_eeq: "[Flame Guard] Огненный щит: бафф на 10с, снижает входящий урон на 50% и наносит периодический урон огнем врагам вокруг героя в радиусе 100.",
  combo_eew: "[Mirror Shield] Прозрачный узкий серп на 10 с (как убывающая луна): выпуклость к врагам, вырез со стороны героя; зона зафиксирована в мире по направлению к курсору. Юниты проходят сквозь. Вражеские снаряды в зоне отражаются с остатком дальности и бьют только врагов; ваши при проходе +15% урона и дальности (один раз на снаряд). Новый каст снимает старую зону.",
  combo_eee: "[Chaos Meteor] Великий метеор: огромный метеор падает в точку, создает ударную волну и затем катится еще 400, оставляя за собой огненный след.",
};

export const SKILLS_CONFIG = {
  global: {
    baseRuneCastTimeSec: 0.3,
    dualRuneSharedCooldownSec: 6.5,
    slotPenaltyByActiveBooks: {
      1: { cdMul: 1.1, powerMul: 0.9 },
      2: { cdMul: 1.15, powerMul: 0.85 },
      3: { cdMul: 1.2, powerMul: 0.8 },
    },
    portal: {
      warmupSec: 1.2,
      openingSec: 15,
      midSec: 45,
      closingSec: 60,
      spawnRateByPhase: { opening: 0.55, mid: 1.0, closing: 0.7 },
      activeEnemyCapBase: 28,
      activeEnemyCapPerWave: 3,
    },
  },
  singleRuneCombos: [
    { id: "rune_q", visualId: "game_skill_rune_q", sequence: "Q", name: "Frost Shard", icon: "❄️", cooldownSec: 0, archetype: "single_ice", damage: 18, runeTier: 1, functionType: "basicCore", desc: SKILL_DESCRIPTIONS.rune_q },
    { id: "rune_w", visualId: "game_skill_rune_w", sequence: "W", name: "Chain Lightning", icon: "⚡", cooldownSec: 0, archetype: "single_lightning", damage: 20, runeTier: 1, functionType: "basicCore", desc: SKILL_DESCRIPTIONS.rune_w },
    { id: "rune_e", visualId: "game_skill_rune_e", sequence: "E", name: "Meteor", icon: "🔥", cooldownSec: 0, archetype: "single_fire", damage: 22, runeTier: 1, functionType: "basicCore", desc: SKILL_DESCRIPTIONS.rune_e },
  ],
  dualRuneCombos: [
    { id: "duo_qq", visualId: "game_skill_duo_qq", sequence: "QQ", name: "Frost Spear", icon: "❄️", cooldownSec: 6.5, archetype: "duo_qq", damage: 22, runeTier: 2, functionType: "tacticalBurst", desc: SKILL_DESCRIPTIONS.duo_qq },
    { id: "duo_qw", visualId: "game_skill_duo_qw", sequence: "QW", name: "Thunderfrost Spear", icon: "⚡", cooldownSec: 6.5, archetype: "duo_qw", damage: 24, runeTier: 2, functionType: "tacticalControl", desc: SKILL_DESCRIPTIONS.duo_qw },
    { id: "duo_qe", visualId: "game_skill_duo_qe", sequence: "QE", name: "Cryo Meteor", icon: "❄️", cooldownSec: 6.5, archetype: "duo_qe", damage: 22, runeTier: 2, functionType: "tacticalBurst", desc: SKILL_DESCRIPTIONS.duo_qe },
    { id: "duo_ww", visualId: "game_skill_duo_ww", sequence: "WW", name: "Chain Storm", icon: "⚡", cooldownSec: 6.5, archetype: "duo_ww", damage: 33, runeTier: 2, functionType: "tacticalControl", desc: SKILL_DESCRIPTIONS.duo_ww },
    { id: "duo_we", visualId: "game_skill_duo_we", sequence: "WE", name: "Ball Lightning", icon: "⚡", cooldownSec: 6.5, archetype: "duo_we", damage: 20, runeTier: 2, functionType: "tacticalBurst", desc: SKILL_DESCRIPTIONS.duo_we },
    { id: "duo_ee", visualId: "game_skill_duo_ee", sequence: "EE", name: "Great Meteor", icon: "🔥", cooldownSec: 6.5, archetype: "duo_ee", damage: 23, runeTier: 2, functionType: "tacticalZone", desc: SKILL_DESCRIPTIONS.duo_ee },
  ],
  invokeCombos: [
    { id: "combo_qqq", visualId: "game_skill_combo_qqq", sequence: "QQQ", name: "Cold Embrace", icon: "❄️", cooldownSec: 28, archetype: "ice_volley", damage: 22, runeTier: 3, functionType: "advancedDefense", desc: SKILL_DESCRIPTIONS.combo_qqq },
    { id: "combo_qqw", visualId: "game_skill_combo_qqw", sequence: "QQW", name: "Frost Nova", icon: "❄️", cooldownSec: 15, archetype: "ice_chain", damage: 18, runeTier: 3, functionType: "advancedArea", desc: SKILL_DESCRIPTIONS.combo_qqw },
    {
      id: "combo_qqe",
      visualId: "game_skill_combo_qqe",
      sequence: "QQE",
      name: "Enhance Armament! Release Recollection!",
      icon: "❄️",
      cooldownSec: 20,
      archetype: "armament_recollection",
      damage: 24,
      runeTier: 3,
      functionType: "advancedArea",
      desc: SKILL_DESCRIPTIONS.combo_qqe,
    },
    { id: "combo_qwq", visualId: "game_skill_combo_qwq", sequence: "QWQ", name: "Frost Ravage", icon: "❄️", cooldownSec: 18, archetype: "ice_bolt", damage: 26, runeTier: 3, functionType: "advancedArea", desc: SKILL_DESCRIPTIONS.combo_qwq },
    { id: "combo_qww", visualId: "game_skill_combo_qww", sequence: "QWW", name: "Fear Aura", icon: "⚡", cooldownSec: 21, archetype: "cone_lightning", damage: 19, runeTier: 3, functionType: "advancedControl", desc: SKILL_DESCRIPTIONS.combo_qww },
    { id: "combo_qwe", visualId: "game_skill_combo_qwe", sequence: "QWE", name: "Teleport", icon: "✨", cooldownSec: 9, archetype: "tri_burst", damage: 20, runeTier: 3, functionType: "advancedDisplacement", desc: SKILL_DESCRIPTIONS.combo_qwe },
    { id: "combo_qeq", visualId: "game_skill_combo_qeq", sequence: "QEQ", name: "Proximity Mine", icon: "❄️", cooldownSec: 10, archetype: "mine_burst", damage: 28, runeTier: 3, functionType: "advancedArea", desc: SKILL_DESCRIPTIONS.combo_qeq },
    { id: "combo_qew", visualId: "game_skill_combo_qew", sequence: "QEW", name: "Fire Ground", icon: "🔥", cooldownSec: 14, archetype: "zone_tick", damage: 16, runeTier: 3, functionType: "advancedArea", desc: SKILL_DESCRIPTIONS.combo_qew },
    { id: "combo_qee", visualId: "game_skill_combo_qee", sequence: "QEE", name: "Frost Resonator", icon: "❄️", cooldownSec: 13, archetype: "ice_resonator", damage: 0, runeTier: 3, functionType: "advancedArea", desc: SKILL_DESCRIPTIONS.combo_qee },
    { id: "combo_wqq", visualId: "game_skill_combo_wqq", sequence: "WQQ", name: "Frost Rain", icon: "⚡", cooldownSec: 14, archetype: "chain_nova", damage: 18, runeTier: 3, functionType: "advancedHybrid", desc: SKILL_DESCRIPTIONS.combo_wqq },
    { id: "combo_wqw", visualId: "game_skill_combo_wqw", sequence: "WQW", name: "Solar Beam", icon: "⚡", cooldownSec: 22, archetype: "lightning_bolt", damage: 30, runeTier: 3, functionType: "advancedProjectile", desc: SKILL_DESCRIPTIONS.combo_wqw },
    { id: "combo_wqe", visualId: "game_skill_combo_wqe", sequence: "WQE", name: "Lightning Dash", icon: "⚡", cooldownSec: 12, archetype: "lightning_burst", damage: 24, runeTier: 3, functionType: "advancedDisplacement", desc: SKILL_DESCRIPTIONS.combo_wqe },
    { id: "combo_wwq", visualId: "game_skill_combo_wwq", sequence: "WWQ", name: "Energy Shield", icon: "⚡", cooldownSec: 18, archetype: "chain_ice", damage: 20, runeTier: 3, functionType: "advancedDefense", desc: SKILL_DESCRIPTIONS.combo_wwq },
    { id: "combo_www", visualId: "game_skill_combo_www", sequence: "WWW", name: "Lightning Anchor", icon: "⚓", cooldownSec: 20, archetype: "lightning_anchor", damage: 0, runeTier: 3, functionType: "advancedControl", desc: SKILL_DESCRIPTIONS.combo_www },
    { id: "combo_wwe", visualId: "game_skill_combo_wwe", sequence: "WWE", name: "Black Hole", icon: "⚡", cooldownSec: 24, archetype: "chain_heavy", damage: 22, runeTier: 3, functionType: "advancedControl", desc: SKILL_DESCRIPTIONS.combo_wwe },
    { id: "combo_weq", visualId: "game_skill_combo_weq", sequence: "WEQ", name: "Repulse", icon: "⚡", cooldownSec: 12, archetype: "freeze_burst", damage: 23, runeTier: 3, functionType: "advancedDisplacement", desc: SKILL_DESCRIPTIONS.combo_weq },
    { id: "combo_wew", visualId: "game_skill_combo_wew", sequence: "WEW", name: "Overcharge", icon: "⚡", cooldownSec: 24, archetype: "delayed_burst", damage: 34, runeTier: 3, functionType: "advancedUtility", desc: SKILL_DESCRIPTIONS.combo_wew },
    { id: "combo_wee", visualId: "game_skill_combo_wee", sequence: "WEE", name: "Mirror Clone", icon: "👤", cooldownSec: 23, archetype: "mirror_clone", damage: 0, runeTier: 3, functionType: "advancedControl", desc: SKILL_DESCRIPTIONS.combo_wee },
    { id: "combo_eqq", visualId: "game_skill_combo_eqq", sequence: "EQQ", name: "Ice Wall", icon: "❄️", cooldownSec: 20, archetype: "fire_ice", damage: 24, runeTier: 3, functionType: "advancedDefense", desc: SKILL_DESCRIPTIONS.combo_eqq },
    { id: "combo_eqw", visualId: "game_skill_combo_eqw", sequence: "EQW", name: "Fire Yo-Yo", icon: "🔥", cooldownSec: 14, archetype: "fire_chain", damage: 25, runeTier: 3, functionType: "advancedProjectile", desc: SKILL_DESCRIPTIONS.combo_eqw },
    { id: "combo_eqe", visualId: "game_skill_combo_eqe", sequence: "EQE", name: "Fire Step", icon: "🔥", cooldownSec: 16, archetype: "fire_bolt", damage: 31, runeTier: 3, functionType: "advancedDisplacement", desc: SKILL_DESCRIPTIONS.combo_eqe },
    { id: "combo_ewq", visualId: "game_skill_combo_ewq", sequence: "EWQ", name: "Gale Force", icon: "🔥", cooldownSec: 14, archetype: "cone_mix", damage: 19, runeTier: 3, functionType: "advancedDisplacement", desc: SKILL_DESCRIPTIONS.combo_ewq },
    { id: "combo_eww", visualId: "game_skill_combo_eww", sequence: "EWW", name: "Volcano Turret", icon: "⚡", cooldownSec: 16, archetype: "storm_area", damage: 23, runeTier: 3, functionType: "advancedArea", desc: SKILL_DESCRIPTIONS.combo_eww },
    { id: "combo_ewe", visualId: "game_skill_combo_ewe", sequence: "EWE", name: "Elemental Fury", icon: "⚡", cooldownSec: 25, archetype: "player_nova", damage: 26, runeTier: 3, functionType: "advancedHybrid", desc: SKILL_DESCRIPTIONS.combo_ewe },
    { id: "combo_eeq", visualId: "game_skill_combo_eeq", sequence: "EEQ", name: "Flame Guard", icon: "🔥", cooldownSec: 20, archetype: "wide_cone", damage: 21, runeTier: 3, functionType: "advancedDefense", desc: SKILL_DESCRIPTIONS.combo_eeq },
    { id: "combo_eew", visualId: "game_skill_combo_eew", sequence: "EEW", name: "Mirror Shield", icon: "🔷", cooldownSec: 16, archetype: "projectile_prism", damage: 0, runeTier: 3, functionType: "advancedArea", desc: SKILL_DESCRIPTIONS.combo_eew },
    { id: "combo_eee", visualId: "game_skill_combo_eee", sequence: "EEE", name: "Chaos Meteor", icon: "🔥", cooldownSec: 26, archetype: "fire_cone", damage: 24, runeTier: 3, functionType: "advancedArea", desc: SKILL_DESCRIPTIONS.combo_eee },
  ],
};
